name: 部署vuepress-theme-bhabgs npm版本

on:
  push:
    branches:
      - release

jobs:
  BUILDDOCS:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@master
      - name: 初始化node环境
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: 安装项目依赖
        run: npm i
      - name: 发布最新版本至npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm publish
      - name: npm 最新版本部署成功通知
        run: |
          npm run deploy:send text=最新版本vuepress-theme-bhabgs以部署至npm title=CINPM-publish通知 url=https://github.com/zx-js/vuepress-theme-bhabgs node .robot/robot.js
